-- Tabela USUARIO
CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    cpf VARCHAR2(11) NOT NULL,
    tipo_usuario VARCHAR2(20) NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    situacao VARCHAR2(20) DEFAULT 'ATIVO',
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT uk_usuario_cpf UNIQUE (cpf)
);
